apiVersion: v1
kind: Template
metadata:
  name: kibana
  labels:
    app: kibana
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: kibana
      labels:
        app: kibana
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      source:
        git:
          uri: https://github.com/King-Of-The-Cookies/deploy_kibana.git
      output:
        to:
          kind: ImageStreamTag
          name: kibana:1
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
