apiVersion: v1
kind: Template
metadata:
  name: kibana-deploy
  labels:
    app: kibana
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      strategy:
        type: Recreate
      replicas: 1
      template:
        metadata:
          name: kibana
          labels:
            app: kibana
            role: kibana
        spec:
          containers:
            - name: kibana
              image: docker.elastic.co/kibana/kibana:7.6.1
              ports:
              - containerPort: 5601
                name: kibana-tcp
                protocol: TCP
              env:
                - name: elasticsearch.username
                  value: elastic
                - name: elasticsearch.password
                  value: 23gv7co7EQgmva9fKmQl
              volumeMounts:
                - name: kibana-config
                  mountPath: /usr/share/kibana/config/kibana.yml
                  subPath: kibana.yml
          volumes:
            - name: kibana-config
              configMap:
                name: kibana-config

  - apiVersion: v1
    kind: Service
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      ports:
        - name: kibana
          port: 5601
          targetPort: 5601
          protocol: TCP
      selector:
        role: kibana

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kibana-config
    data:
      kibana.yml: ${KIBANA_YML}

parameters:
  - name: KIBANA_YML
    value: |
      server.name: kibana
      server.host: "0"
      elasticsearch.hosts: [ "http://elasticsearch:9200" ]
      elasticsearch.username: "kibana"
      elasticsearch.password: "23gv7co7EQgmva9fKmQl"
