apiVersion: v1
kind: Template
metadata:
  name: kibana-deploy
  labels:
    app: kibana
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      strategy:
        type: Recreate
      replicas: 1
      template:
        metadata:
          name: kibana
          labels:
            app: kibana
            role: kibana
        spec:
          containers:
            - name: kibana
              image: 172.30.1.1:5000/test/kibana:1
              ports:
              - containerPort: 5601
                name: kibana-tcp
                protocol: TCP
              env:
                - name: elasticsearch.username
                  value: elastic
                - name: elasticsearch.password
                  value: 23gv7co7EQgmva9fKmQl

  - apiVersion: v1
    kind: Service
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      ports:
        - name: kibana
          port: 5601
          targetPort: 5601
          protocol: TCP
      selector:
        role: kibana
